language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/SLE-12-GA/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "yast2-devtools rake" -g yast-rake
script:
    - make -f Makefile.cvs
    - make
    - sudo make install
    - make check
    - rake check_rng_status

